services:
  frontend:
    build: 
      context: .
      target: builder
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
